// <auto-generated />
using System;
using EngWordApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngWordApp.Migrations
{
    [DbContext(typeof(WordContext))]
    partial class WordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EngWordApp.Entity.Mean", b =>
                {
                    b.Property<int>("MeanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeanId"));

                    b.Property<string>("TrMean")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("MeanId");

                    b.HasIndex("WordId");

                    b.ToTable("Means");
                });

            modelBuilder.Entity("EngWordApp.Entity.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<int>("AskCount")
                        .HasColumnType("int");

                    b.Property<bool?>("Connective")
                        .HasColumnType("bit");

                    b.Property<string>("EngWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAsked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAsked")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ScAnswerCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SuccessPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Weak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WordLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WrongAnswerCount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WordId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("EngWordApp.Entity.Mean", b =>
                {
                    b.HasOne("EngWordApp.Entity.Word", "Word")
                        .WithMany("Means")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EngWordApp.Entity.Word", b =>
                {
                    b.Navigation("Means");
                });
#pragma warning restore 612, 618
        }
    }
}
